development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:e0a4053281cce2e73198f037afdc2838@pike.redistogo.com:11185/
  channel_prefix: trello_production
